spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: '@Lizecheng135'
  jpa:
    hibernate:
      ddl-auto: update
    show-sqp: true

logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog-dev.log
server:
  port: 8887